import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import {ThemeProvider} from "@/context/themeContext";
import Navbar from "@/components/NavBar";
import {NextIntlClientProvider} from "next-intl";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
      <NextIntlClientProvider>
          <ThemeProvider attribute="class">
              <Navbar/>
              {children}
          </ThemeProvider>
      </NextIntlClientProvider>

      </body>

    </html>
  );
}
